### ISSUE TITLE
composer/packagist usage

### ISSUE THREAD

**Issue by raffaelj** [pauloamgomes/CockpitCms-EditorFormats#11]
Could you add this repo to your composer packages, please?

Since I [discovered][1] the ability to use composer for dependency management of cockpit addons, I really like that workflow.

I'll send a PR in a few minutes, so you only have to submit the repo link to your existing composer profile.

[1]: https://github.com/piotr-cz/cockpit-sql-driver#using-composer

**Comment by pauloamgomes** [comment]
Thanks @raffaelj , submitted!

**Comment by raffaelj** [comment]
Thanks. Now I can require `pauloamgomes/cockpit-editorformats:dev-master` successfully.
