### ISSUE TITLE
Manage formats

### ISSUE THREAD

**Issue by tanc** [pauloamgomes/CockpitCms-EditorFormats#5]
Hi, thanks for this plugin, very useful. Just wondering if there is any way to manage what is displayed in the formats menu? I'd like to limit the options there to just paragraph, h2 and h3.

**Comment by pauloamgomes** [comment]
Hey @tanc , I'll check and confirm when have few free time.

**Comment by pauloamgomes** [comment]
Sorry for the delay, it's supported now via https://github.com/pauloamgomes/CockpitCms-EditorFormats/commit/8bab9648c12430bed2b7ff709099341d99ab8872

There is a new option (Block Formats) that permit to enable/disable:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/102261/65805149-5d5bc380-e17c-11e9-9743-552d5a9e6da5.png">
