### ISSUE TITLE
"access" permission needed if not in admin user group

### ISSUE THREAD

**Issue by raffaelj** [pauloamgomes/CockpitCms-EditorFormats#6]
You missed a note in the README, to add a user group acl `editorformats` - `access: true`, because you use `App.callmodule`, which always requires an acl action.

I would suggest, to add another endpoint to `Admin.php`, that calls `getEditorFormat()`. This way you don't need this extra access rule. Than call it with `App.request` instead.

I think, using the editor format without a rule is the expected behavior. And you can't forget it by accident when adding more user groups.

**Comment by pauloamgomes** [comment]
Hi @raffaelj , thanks, I updated the readme to include details about the required permissions.
