### ISSUE TITLE
Doesn't work on repeater fields with WYSIWYG

### ISSUE THREAD

**Issue by Blemming** [pauloamgomes/CockpitCms-EditorFormats#7]
On repeater fields you can use any other field you just have to set it in the options, when I set wysiwyg and give it an editor format it just uses the normal default one :
```
  "fields": [
    {
      "type": "wysiwyg",
      "label": "Wysiwig",
      "options": {
          "editor": {
            "format": "Advanced"
         }
      }
    },
    {
      "type": "image",
      "label": "Image"
    }
```

**Comment by pauloamgomes** [comment]
Hi @Blemming , it works, please check below:

I'm using the following JSON definition:

```json
{
"fields": [
    {
      "type": "wysiwyg",
      "label": "Wysiwig",
      "options": {
          "editor": {
            "format": "Basic"
         }
      }
    },
    {
      "type": "image",
      "label": "Image"
    }
  ]
}
```

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/102261/65801548-42378680-e171-11e9-838d-fe6ec46dce58.png">

So when adding the field:

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/102261/65801606-62674580-e171-11e9-9703-272ab7603c0b.png">

And my configured Editor Format:

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/102261/65801656-7dd25080-e171-11e9-8c05-1b9eb29b6b58.png">

**Comment by Blemming** [comment]
Oh for some reason it works now, maybe I was missing an ctrl+F5 or something 🤷‍♂️
Thank you anyways
