### ISSUE TITLE
language files are now stored in /storage/assets

### ISSUE THREAD

**Issue by raffaelj** [pauloamgomes/CockpitCms-EditorFormats#8]
With the new `COCKPIT_ENV_ROOT` constant, custom files don't have to be in `/cockpit/config` anymore. While fiddling with all the new possibilities, the tiny mce language files didn't load anymore. @aheinze fixed it a month ago and the tinymce language files now have to be in `COCKPIT_PUBLIC_STORAGE_FOLDER/assets/cockpit/i18n/tinymce/de.js`

fix: https://github.com/agentejo/cockpit/commit/d9f75ec94b09b7e4e7d23dd795570241f7b91908
discussion: https://github.com/agentejo/cockpit/issues/1186

If you would change it (or if I should send a PR), it wouldn't be backwards compatible.

My workaround is, to store the TinyMCE language files in both locations, `/cockpit/config/cockpit/i18n/tinymce/de.js` and `/my/custom/config/cockpit/i18n/tinymce/de.js`.

**Comment by pauloamgomes** [comment]
Thanks @raffaelj , can you kindly do a PR? (I'm aware that will not be backwards compatible.)

**Comment by raffaelj** [comment]
I'll send a PR in the next days.
